# Generated by Django 4.2.1 on 2023-06-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_osp_descriptions_alter_osp_parent_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osp',
            name='parent_images',
            field=models.ImageField(blank=True, null=True, upload_to='parent_image/', verbose_name='Ваша фото'),
        ),
    ]
