# Generated by Django 4.2.1 on 2023-06-01 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_osp_parent_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osp',
            old_name='descriptions',
            new_name='description',
        ),
    ]
