# Generated by Django 4.2.1 on 2023-06-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_osp_parent_images_osp_parent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osp',
            name='parent_image',
            field=models.ImageField(blank=True, null=True, upload_to='parent_images/', verbose_name='Ваша фото'),
        ),
    ]
