# Generated by Django 4.2.1 on 2023-06-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_osp_parent_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OSP',
        ),
    ]
